# Welcome to Jekyll!
title: Astragroup Status Updates
email: admin@astragroup.info
description: >-
  A micro-blog for status updates relating to various AG services.
  (Hosting, NextCloud, Gitea, Etc.)
baseurl: ""
url: "https://status.astragroup.info"
github_username:  nate2014jatc
# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
theme: jekyll-theme-hacker
host: 0.0.0.0
paginate: 5
timezone: America/Denver
encoding: utf-8
livereload: true
livereload_min_delay: 60
livereload_max_delay: 600
author: RaxVentus