name: NTFY Manual Ping
run-name: ${{ github.actor }} has submitted a page build.
on: [page_build]
jobs:
  NTFY-Manual-Ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - name: Ping NTFY server with update message.
        run: |
          curl ntfy.sh \
          -d '{
            "topic": "Hgh543VzdawHYbZw",
            "message": "The site has been updated.",
            "actions": [
              {
                "action": "view",
                "label": "Visit Site",
                "url": "https://status.astragroup.info/"
              }
            ]
          }'
      - run: echo "Job status is ${{ job.status }}"
